pipeline:
  # pr
  run-integration-tests:
    image: casperlabs/buildenv:latest
    commands:
      - python3 -m pip install pipenv dataclasses typing_extensions
      - cd integration-testing
      - ./run_tests.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp